ITM-510
NextCenturyCorporation/itm-evaluation-server pull request #86
Opened 2024-07-11 14:20 UTC by Ayal-Ciobotaru

Added 'justification' as a requirement for `action` and added `medical_supplies` controlled vocab

2024-07-11 14:53 UTC, Ayal-Ciobotaru commented
Adjusting based on discussion with Darren

2024-07-11 17:13 UTC, nextcen-dgemoets reviewed
Obviously I'll test after the client PR is re-opened, but here are some preliminary comments.

2024-07-11 17:13 UTC, nextcen-dgemoets commented on swagger/swagger.yaml
> +      description: Directives issued by competent military authority
Could you change "Neutral" to "Treat All Neutrally"?

2024-07-11 17:13 UTC, nextcen-dgemoets commented on swagger/swagger.yaml
> +          description: A list of medical policies
Could you add, "; omit this property if no special policy is in place."

2024-07-11 17:13 UTC, nextcen-dgemoets commented on swagger/swagger.yaml
> +          description: Invalid action or Session ID, empty justification or specified an intent action
Although this is true, we're not listing any other reasons the action can be invalid...so probably just leave it how it was before.

2024-07-11 19:51 UTC, nextcen-dgemoets requested changes
Need to fix the sample; otherwise looks good.

2024-07-11 19:51 UTC, nextcen-dgemoets commented on swagger_server/itm/data/dryrun/test/sample.yaml
> +    medical_policies: Treat All Neutrally # controlled vocab includes Treat All Neutrally, Treat Enemy LLE, Treat Civilian LLE, and Prioritize Mission
This string needs to be converted into an array with one string.

2024-07-11 19:51 UTC, nextcen-dgemoets commented on swagger_server/itm/data/metrics/test/sample.yaml
> +    medical_policies: Treat All Neutrally # controlled vocab includes Treat All Neutrally, Treat Enemy LLE, Treat Civilian LLE, and Prioritize Mission
This string needs to be converted into an array with one string.

2024-07-12 13:05 UTC, nextcen-dgemoets approved these changes

2024-07-12 20:24 UTC, dereknop approved these changes

2024-07-12 21:20 UTC, merged